version: "3"
services:
  ntopng-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ntopng-docker:v1.0.0
    restart: always
    command: -w 0.0.0.0:443
    ports:
      - 443:3000/tcp
    network_mode: host

