version: "2"
services:
  ntopng:
    image: ppcelery/ntopng-docker
    restart: always
    logging:
      driver: syslog
      options:
        syslog-facility: local6
        tag: ntopng
    network_mode: host
    volumes:
      - /var/lib/ntopng:/var/tmp/ntopng
    command: -w 0.0.0.0:443 -r localhost:6379 -Z "/monitor"
  redis:
    image: redis:3.0
    restart: always
    logging:
      driver: syslog
      options:
        syslog-facility: local6
        tag: redis
    ports:
      - 6379:6379

networks:
  default:
    driver: bridge
